"""create agent call transcripts table

Revision ID: 0d4cad83a0e3
Revises: 1a7b46e284b4
Create Date: 2026-08-25 12:04:38.889272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4cad83a0e3'
down_revision: Union[str, Sequence[str], None] = '1a7b46e284b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_call_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_call_id'], ['agent_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_call_transcripts_id'), 'agent_call_transcripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_call_transcripts_id'), table_name='agent_call_transcripts')
    op.drop_table('agent_call_transcripts')
    # ### end Alembic commands ###
