"""create agent calls table

Revision ID: 1a7b46e284b4
Revises: 19419ee22860
Create Date: 2026-08-25 00:35:51.678022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7b46e284b4'
down_revision: Union[str, Sequence[str], None] = '19419ee22860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('caller_name', sa.String(), nullable=True),
    sa.Column('caller_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('provider_call_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_calls_id'), 'agent_calls', ['id'], unique=False)
    op.create_index(op.f('ix_agent_calls_provider_call_id'), 'agent_calls', ['provider_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_calls_provider_call_id'), table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_id'), table_name='agent_calls')
    op.drop_table('agent_calls')
    # ### end Alembic commands ###
