"""add demo requests

Revision ID: 529d6383bc92
Revises: 8187972637d4
Create Date: 2026-09-05 08:08:04.965803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529d6383bc92'
down_revision: Union[str, Sequence[str], None] = '8187972637d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_requests_email'), 'demo_requests', ['email'], unique=False)
    op.create_index(op.f('ix_demo_requests_id'), 'demo_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_requests_id'), table_name='demo_requests')
    op.drop_index(op.f('ix_demo_requests_email'), table_name='demo_requests')
    op.drop_table('demo_requests')
    # ### end Alembic commands ###
