"""add sla_days to pipeline stages

Revision ID: 5fef38a37876
Revises: faf8515e8c10
Create Date: 2026-07-11 21:32:13.078781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fef38a37876'
down_revision: Union[str, Sequence[str], None] = 'faf8515e8c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_stages', sa.Column('sla_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_stages', 'sla_days')
    # ### end Alembic commands ###
