"""create follow up tasks table

Revision ID: 8187972637d4
Revises: 991d668e0c0e
Create Date: 2026-08-26 00:08:17.011474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8187972637d4'
down_revision: Union[str, Sequence[str], None] = '991d668e0c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_call_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_agent_call_id'), 'follow_up_tasks', ['agent_call_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_id'), 'follow_up_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_tasks_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_agent_call_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    # ### end Alembic commands ###
