"""create agent call intelligence table

Revision ID: 991d668e0c0e
Revises: 9ea1d60433c8
Create Date: 2026-08-25 23:49:54.826825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991d668e0c0e'
down_revision: Union[str, Sequence[str], None] = '9ea1d60433c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_call_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('lead_temperature', sa.String(length=50), nullable=True),
    sa.Column('customer_intent', sa.String(length=100), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('buying_signals', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_call_intelligence_agent_call_id'), 'agent_call_intelligence', ['agent_call_id'], unique=True)
    op.create_index(op.f('ix_agent_call_intelligence_id'), 'agent_call_intelligence', ['id'], unique=False)
    op.drop_column('agent_calls', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_calls', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_call_intelligence_id'), table_name='agent_call_intelligence')
    op.drop_index(op.f('ix_agent_call_intelligence_agent_call_id'), table_name='agent_call_intelligence')
    op.drop_table('agent_call_intelligence')
    # ### end Alembic commands ###
