"""create agent call summaries table

Revision ID: 9ea1d60433c8
Revises: 0d4cad83a0e3
Create Date: 2026-08-25 12:26:54.443532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea1d60433c8'
down_revision: Union[str, Sequence[str], None] = '0d4cad83a0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_call_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_call_id'], ['agent_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_call_id')
    )
    op.create_index(op.f('ix_agent_call_summaries_id'), 'agent_call_summaries', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_call_summaries_id'), table_name='agent_call_summaries')
    op.drop_table('agent_call_summaries')
    # ### end Alembic commands ###
